name: svg_to_path_annotation
description: Svg to path generator annotation
version: 0.0.1
author:
homepage:

environment:
  sdk: '>=2.12.0-0 <3.0.0'
#  flutter: ">=1.17.0"

dependencies:
#  flutter:
#    sdk: flutter

dev_dependencies:
#  flutter_test:
#    sdk: flutter

#flutter: